theme: jekyll-theme-minimal
title: Benedick Asdyo
description: Currently I'm a Computer Science and Mathematics student at Bina Nusantara University. I enjoy solving problems and learn new things.
logo : https://media-exp1.licdn.com/dms/image/C5603AQFeEZxp62tg4g/profile-displayphoto-shrink_200_200/0/1604054449044?e=1624492800&v=beta&t=L3OfecYN2fCA7bJE8F_dG3SKInnLOfXb33o8IGFCZ-o

