theme: jekyll-theme-minimal
title: Benedick Asdyo
description: ## 🧑About Me _Currently I'm a Computer Science and Mathematics student at Bina Nusantara University. I enjoy solving problems and learn new things._ <br><br>
Contact me : [Email](mailto:bens_91@yahoo.co.id)/[LinkedIn](https://www.linkedin.com/in/benedick-asdyo-997b981a2/)/[Facebook](https://web.facebook.com/ben.lijaya/)/[GitHub](https://github.com/benedicka)/[ICPC ID](https://icpc.global/ICPCID/TAWR9334OEVN)
logo : https://media-exp1.licdn.com/dms/image/C5603AQFeEZxp62tg4g/profile-displayphoto-shrink_200_200/0/1604054449044?e=1624492800&v=beta&t=L3OfecYN2fCA7bJE8F_dG3SKInnLOfXb33o8IGFCZ-o

